{
  "name": "ptbizsms-dashboard",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "concurrently \"npm run dev:frontend\" \"npm run dev:mock-server\"",
    "dev:frontend": "vite",
    "dev:mock-server": "json-server --watch mock-server/db.json --port 3001 --delay 500 --routes mock-server/routes.json",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "test": "vitest run",
    "test:watch": "vitest",
    "test:coverage": "vitest run --coverage",
    "typecheck": "tsc --noEmit",
    "lint": "biome check src",
    "format": "biome format src --write",
    "performance:audit": "lighthouse http://localhost:3000 --config=lighthouse.config.js",
    "accessibility:audit": "axe http://localhost:3000 --config=accessibility.config.js",
    "a11y:check": "node scripts/accessibility-check.js",
    "security:scan": "npm audit --audit-level=high",
    "monitoring:test": "node scripts/monitoring-test.js",
    "design-system:check": "node scripts/design-system-check.js",
    "hooks:test": "node scripts/hooks-test.js",
    "validation:test": "node scripts/validation-test.js",
    "test:unit": "vitest run --config vitest.config.ts",
    "test:component": "vitest run --config vitest.config.ts --mode component",
    "test:integration": "vitest run --config vitest.config.ts --mode integration"
  },
  "dependencies": {
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-toast": "^1.1.5",
    "@sentry/react": "^7.106.0",
    "@tanstack/react-query": "^5.28.4",
    "@tanstack/react-query-devtools": "^5.28.4",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "jwt-decode": "^4.0.0",
    "react": "^19.0.0-beta-26f2416093-20240202",
    "react-dom": "^19.0.0-beta-26f2416093-20240202",
    "react-router-dom": "^6.22.3",
    "tailwind-merge": "^2.2.2",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@axe-core/react": "^4.7.3",
    "@biomejs/biome": "^1.6.3",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/typography": "^0.5.10",
    "@testing-library/jest-dom": "^6.3.0",
    "@testing-library/react": "^14.2.1",
    "@testing-library/react-hooks": "^8.0.1",
    "@types/jwt-decode": "^3.1.0",
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@vitejs/plugin-react-swc": "^3.6.0",
    "@vitest/coverage-v8": "^1.4.0",
    "autoprefixer": "^10.4.19",
    "axe-core": "^4.7.2",
    "concurrently": "^8.2.2",
    "json-server": "^0.17.4",
    "jsdom": "^24.0.0",
    "lighthouse": "^11.0.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.4.2",
    "vite": "^5.2.8",
    "vitest": "^1.4.0"
  }
}