"""
Post test Block Kit cards to #alowaresmsupdates so you can see exactly
what the bot produces in Slack. Run with:
  python3 sms-insights/scripts/post-test-cards.py
"""
import json
import os
import urllib.request

BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN", "").strip()
CHANNEL   = "C09ULGH1BEC"   # #alowaresmsupdates
DASHBOARD = "https://ptbizsms.com/v2/runs"

if not BOT_TOKEN:
    raise RuntimeError("SLACK_BOT_TOKEN is required")

def post(blocks, text, thread_ts=None):
    payload = {"channel": CHANNEL, "text": text, "blocks": blocks}
    if thread_ts:
        payload["thread_ts"] = thread_ts
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://slack.com/api/chat.postMessage",
        data=body,
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {BOT_TOKEN}"},
        method="POST",
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())

# ── 1. Daily Snapshot Card ────────────────────────────────────────────────────
snapshot_blocks = [
    {
        "type": "header",
        "text": {"type": "plain_text", "text": "📊 Daily SMS Snapshot — Jun 12, 2025", "emoji": True}
    },
    {"type": "divider"},
    {
        "type": "section",
        "fields": [
            {"type": "mrkdwn", "text": "*Total Messages*\n3,847"},
            {"type": "mrkdwn", "text": "*Inbound Replies*\n412  *(10.7%)*"},
            {"type": "mrkdwn", "text": "*Booked Calls*\n🟢 18"},
            {"type": "mrkdwn", "text": "*Opt-Outs*\n🟢 3  *(0.08%)*"},
        ]
    },
    {
        "type": "section",
        "fields": [
            {"type": "mrkdwn", "text": "*Reply Rate*\n🟡 10.7%  `▓▓▓░░`"},
            {"type": "mrkdwn", "text": "*Median Reply Time*\n🟢 14 min"},
            {"type": "mrkdwn", "text": "*Active Sequences*\n7"},
            {"type": "mrkdwn", "text": "*New Leads*\n94"},
        ]
    },
    {
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "🟢 *Signal:* Strong booking day — 18 calls booked, opt-out rate well below threshold. Reply rate slightly below target but median response time is healthy at 14 min."
        }
    },
    {"type": "divider"},
    {
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "📋 Full Report", "emoji": True},
                "action_id": "sms_report_view_full",
                "value": json.dumps({"channelId": CHANNEL, "prompt": "daily report"}),
                "style": "primary"
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "📅 Yesterday", "emoji": True},
                "action_id": "sms_report_view_yesterday",
                "value": json.dumps({"channelId": CHANNEL})
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "🔄 Refresh", "emoji": True},
                "action_id": "sms_report_refresh",
                "value": json.dumps({"channelId": CHANNEL, "prompt": "daily report"})
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "📊 Scoreboard", "emoji": True},
                "action_id": "sms_scoreboard_view",
                "value": json.dumps({"channelId": CHANNEL})
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "🌐 Dashboard", "emoji": True},
                "action_id": "sms_report_open_dashboard",
                "url": DASHBOARD
            }
        ]
    },
    {
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated by SMS Insights bot  •  <{DASHBOARD}|Open Dashboard>  •  Password-protected access"}
        ]
    }
]

print("Posting daily snapshot card...")
r1 = post(snapshot_blocks, "Daily SMS Snapshot — Jun 12, 2025")
if r1.get("ok"):
    parent_ts = r1["ts"]
    print(f"  ✅ Posted (ts={parent_ts})")
else:
    print(f"  ❌ Failed: {r1.get('error')}")
    parent_ts = None

# ── 2. Full report text in thread ─────────────────────────────────────────────
if parent_ts:
    thread_text = (
        "*Full Report — Jun 12, 2025*\n\n"
        "*DAILY SMS SNAPSHOT — June 12, 2025*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "*VOLUME*\n"
        "• Total messages sent: 3,847\n"
        "• Inbound replies: 412 (10.7%)\n"
        "• New leads contacted: 94\n\n"
        "*CONVERSIONS*\n"
        "• Booked calls: 18 ✅\n"
        "• Qualified leads: 31\n"
        "• Opt-outs: 3 (0.08%) ✅\n\n"
        "*RESPONSE METRICS*\n"
        "• Median reply time: 14 min ✅\n"
        "• Replies within 5 min: 38%\n"
        "• Replies within 30 min: 71%\n\n"
        "*TOP SEQUENCES*\n"
        "1. Cold Outreach v3 — 1,204 sent, 8.2% reply\n"
        "2. Re-engagement Q2 — 892 sent, 14.1% reply\n"
        "3. Follow-up Day 3 — 641 sent, 11.8% reply\n\n"
        "*SETTER ACTIVITY*\n"
        "• Alex R: 6 bookings, 94% compliance\n"
        "• Jordan M: 5 bookings, 97% compliance\n"
        "• Casey T: 4 bookings, 91% compliance\n"
        "• Morgan L: 3 bookings, 88% compliance"
    )
    r2 = post(
        [{"type": "section", "text": {"type": "mrkdwn", "text": thread_text}}],
        "Full Report",
        thread_ts=parent_ts
    )
    print(f"  {'✅' if r2.get('ok') else '❌'} Thread reply posted")

# ── 3. Scoreboard Card ────────────────────────────────────────────────────────
scoreboard_blocks = [
    {
        "type": "header",
        "text": {"type": "plain_text", "text": "🏆 Weekly Setter Scoreboard — Week of Jun 9", "emoji": True}
    },
    {"type": "divider"},
    {
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": (
                "*🥇 Alex R*\n"
                "> Bookings: *18*  •  Sequences: *3*  •  Reply Rate: *12.4%*  •  Compliance: *94%*\n"
                "> `▓▓▓▓▓▓▓▓▓▓` 100 pts\n\n"
                "*🥈 Jordan M*\n"
                "> Bookings: *15*  •  Sequences: *3*  •  Reply Rate: *14.1%*  •  Compliance: *97%*\n"
                "> `▓▓▓▓▓▓▓▓░░` 87 pts\n\n"
                "*🥉 Casey T*\n"
                "> Bookings: *12*  •  Sequences: *2*  •  Reply Rate: *11.8%*  •  Compliance: *91%*\n"
                "> `▓▓▓▓▓▓▓░░░` 74 pts\n\n"
                "*4. Morgan L*\n"
                "> Bookings: *9*  •  Sequences: *2*  •  Reply Rate: *9.3%*  •  Compliance: *88%*\n"
                "> `▓▓▓▓▓░░░░░` 58 pts\n\n"
                "*5. Riley K*\n"
                "> Bookings: *6*  •  Sequences: *1*  •  Reply Rate: *7.1%*  •  Compliance: *85%*\n"
                "> `▓▓▓░░░░░░░` 41 pts"
            )
        }
    },
    {"type": "divider"},
    {
        "type": "section",
        "fields": [
            {"type": "mrkdwn", "text": "*Team Total Bookings*\n60"},
            {"type": "mrkdwn", "text": "*Team Reply Rate*\n🟡 11.0%"},
            {"type": "mrkdwn", "text": "*Avg Compliance*\n🟢 91%"},
            {"type": "mrkdwn", "text": "*Total Messages*\n18,420"},
        ]
    },
    {
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "🔄 Refresh Scoreboard", "emoji": True},
                "action_id": "sms_scoreboard_refresh",
                "value": json.dumps({"channelId": CHANNEL}),
                "style": "primary"
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "🌐 Dashboard", "emoji": True},
                "action_id": "sms_report_open_dashboard",
                "url": DASHBOARD
            }
        ]
    },
    {
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"SMS Insights  •  Week of Jun 9–15, 2025  •  <{DASHBOARD}|View Full Dashboard>"}
        ]
    }
]

print("\nPosting scoreboard card...")
r3 = post(scoreboard_blocks, "Weekly Setter Scoreboard — Week of Jun 9")
if r3.get("ok"):
    print(f"  ✅ Posted (ts={r3['ts']})")
else:
    print(f"  ❌ Failed: {r3.get('error')}")

print("\nDone! Check #alowaresmsupdates in Slack.")
