[phases.setup]
nixPkgs = ['nodejs-22_v22_15_1']

# Ensure PATH includes node_modules/.bin
[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.runtime]
nixPkgs = ['nodejs-22_v22_15_1']

